# Numpy

## Mengingat list

- *powerfull*
- Koleksi dari nilai
- Menampung berbagai macam tipe data
- Mengganti, Menambah, Mengurangi
- Kebutuhan untuk Data Science: Operasi Matematika antar list, *speed*

In [3]:
tinggi = [1.73, 1.68, 1.71, 1.89, 1.69]

In [4]:
tinggi

[1.73, 1.68, 1.71, 1.89, 1.69]

In [5]:
berat = [65.4, 59.2, 63.6, 88.4, 68.7]

In [6]:
berat / tinggi ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Solusi? Numpy

- Python Numerik
- Alternatif dari list python: NumPy Array
- Kalkulasi semua elemen array
- Mudah dan Cepat

In [7]:
import numpy as np
np_tinggi = np.array(tinggi)
np_tinggi

array([ 1.73,  1.68,  1.71,  1.89,  1.69])

In [8]:
np_berat = np.array(berat)

In [9]:
np_berat

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [10]:
bmi = np_berat / np_tinggi ** 2

In [11]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  24.05377963])

## Numpy remarks

In [12]:
np.array([1.0, 'is', True]) # Numpy hanya dapat menampung satu tipe

array(['1.0', 'is', 'True'], 
      dtype='|S32')

In [13]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [14]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [15]:
numpy_array + numpy_array 

array([2, 4, 6])

## Numpy subsetting

In [16]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  24.05377963])

In [17]:
bmi[1]

20.975056689342409

In [18]:
bmi > 23

array([False, False, False,  True,  True], dtype=bool)

In [19]:
bmi[bmi > 23]

array([ 24.7473475 ,  24.05377963])

## 2D Numpy arrays

In [20]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.69])
np_berat = np.array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [21]:
type(np_tinggi)

numpy.ndarray

In [22]:
type(np_berat)

numpy.ndarray

In [23]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  68.7]])


In [24]:
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.69],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]])

In [25]:
np_2d.shape

(2, 5)

In [26]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  "68.7"]])

In [27]:
np_2d # Ingat hanya bisa satu tipe

array([['1.73', '1.68', '1.71', '1.89', '1.69'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], 
      dtype='|S32')

## Nubsetting Numpy 2D

In [28]:
np_2d[0]

array(['1.73', '1.68', '1.71', '1.89', '1.69'], 
      dtype='|S32')

In [29]:
np_2d[0][2]

'1.71'

In [30]:
np_2d[0,2]

'1.71'

In [31]:
np_2d[:,1:3]

array([['1.68', '1.71'],
       ['59.2', '63.6']], 
      dtype='|S32')

In [32]:
np_2d[1,:]

array(['65.4', '59.2', '63.6', '88.4', '68.7'], 
      dtype='|S32')

## Searching

In [38]:
search = np.array([1,2,3,4,5,3,2,3,4])
search

array([1, 2, 3, 4, 5, 3, 2, 3, 4])

In [41]:
index_search = np.where(search == 3)
index_search

(array([2, 5, 7]),)

In [42]:
np.take(search,index_search)

array([[3, 3, 3]])

In [45]:
np.max(search), np.min(search), np.mean(search)

(5, 1, 3.0)

## matrix 

In [51]:
matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_2 = np.array([[1,2],[2,2],[3,3]])

In [52]:
matrix_1.shape, matrix_2.shape

((2, 3), (3, 2))

In [53]:
np.dot(matrix_1,matrix_2)

array([[14, 15],
       [32, 36]])

In [55]:
matrix_1 - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
np.dot(matrix_2,matrix_1)

array([[ 9, 12, 15],
       [10, 14, 18],
       [15, 21, 27]])